// Copyright 2026 Orican Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use super::*;

fn unique_temp_dir() -> PathBuf {
    let dir = std::env::temp_dir().join(format!("ratect-cache-test-{}", uuid::Uuid::new_v4()));
    fs::create_dir_all(&dir).unwrap();
    dir
}

#[test]
fn project_cache_key_generates_and_persists_a_key() {
    let dir = unique_temp_dir();

    let first = project_cache_key(&dir).unwrap();
    let second = project_cache_key(&dir).unwrap();

    assert_eq!(first, second);
    assert!(cache_directory(&dir).join("key").exists());

    fs::remove_dir_all(&dir).unwrap();
}

#[test]
fn project_cache_key_reads_an_existing_batect_style_key_file() {
    let dir = unique_temp_dir();
    let caches_dir = cache_directory(&dir);
    fs::create_dir_all(&caches_dir).unwrap();
    fs::write(
        caches_dir.join("key"),
        "# This file was autogenerated by Batect to track which Docker volumes are \
             associated with this project.\n# Do not modify it, and do not commit it to source \
             control.\nabc123\n",
    )
    .unwrap();

    let key = project_cache_key(&dir).unwrap();

    assert_eq!(key, "abc123");

    fs::remove_dir_all(&dir).unwrap();
}

#[test]
fn cache_volume_name_uses_the_batect_cache_prefix() {
    assert_eq!(
        cache_volume_name("abc123", "gradle-cache"),
        "batect-cache-abc123-gradle-cache"
    );
}

#[test]
fn resolve_cache_mount_builds_a_volume_bind_string() {
    let dir = unique_temp_dir();
    let options = CacheOptions {
        cache_type: CacheType::Volume,
        project_directory: dir.clone(),
    };
    let mount = CacheVolumeMount {
        name: "gradle-cache".to_string(),
        container: "/root/.gradle".to_string(),
        options: None,
        scope: Default::default(),
    };

    let resolved = resolve_cache_mount(&options, "abc123", &mount).unwrap();

    assert_eq!(resolved, "batect-cache-abc123-gradle-cache:/root/.gradle");

    fs::remove_dir_all(&dir).unwrap();
}

#[test]
fn resolve_cache_mount_includes_options_when_given() {
    let dir = unique_temp_dir();
    let options = CacheOptions {
        cache_type: CacheType::Volume,
        project_directory: dir.clone(),
    };
    let mount = CacheVolumeMount {
        name: "gradle-cache".to_string(),
        container: "/root/.gradle".to_string(),
        options: Some("ro".to_string()),
        scope: Default::default(),
    };

    let resolved = resolve_cache_mount(&options, "abc123", &mount).unwrap();

    assert_eq!(
        resolved,
        "batect-cache-abc123-gradle-cache:/root/.gradle:ro"
    );

    fs::remove_dir_all(&dir).unwrap();
}

#[test]
fn resolve_cache_mount_creates_and_uses_a_host_directory_for_directory_type() {
    let dir = unique_temp_dir();
    let options = CacheOptions {
        cache_type: CacheType::Directory,
        project_directory: dir.clone(),
    };
    let mount = CacheVolumeMount {
        name: "gradle-cache".to_string(),
        container: "/root/.gradle".to_string(),
        options: None,
        scope: Default::default(),
    };

    let resolved = resolve_cache_mount(&options, "abc123", &mount).unwrap();

    let expected_dir = cache_directory(&dir).join("gradle-cache");
    assert_eq!(
        resolved,
        format!("{}:/root/.gradle", expected_dir.display())
    );
    assert!(expected_dir.is_dir());

    fs::remove_dir_all(&dir).unwrap();
}

// `clean_volume_caches`'s own async glue (list, filter, remove each) is
// thin enough to be covered by the real end-to-end Docker test in
// `tests/cli.rs` instead of a dedicated fake `ContainerRuntime` here —
// the interesting decision logic is `matching_cache_volumes`, a plain
// synchronous function these tests exercise directly.

#[test]
fn matching_cache_volumes_matches_only_this_projects_prefix() {
    let existing = vec![
        "batect-cache-abc123-gradle-cache".to_string(),
        "batect-cache-different-key-gradle-cache".to_string(),
        "some-unrelated-volume".to_string(),
    ];

    let matched =
        matching_cache_volumes(&existing, &cache_volume_name("abc123", ""), &HashSet::new());

    assert_eq!(matched, vec!["batect-cache-abc123-gradle-cache"]);
}

#[test]
fn matching_cache_volumes_restricts_to_the_only_set_when_given() {
    let existing = vec![
        "batect-cache-abc123-gradle-cache".to_string(),
        "batect-cache-abc123-npm-cache".to_string(),
    ];
    let only = HashSet::from(["npm-cache".to_string()]);

    let matched = matching_cache_volumes(&existing, &cache_volume_name("abc123", ""), &only);

    assert_eq!(matched, vec!["batect-cache-abc123-npm-cache"]);
}

#[test]
fn matching_cache_volumes_is_empty_when_nothing_matches_the_prefix() {
    let existing = vec!["some-unrelated-volume".to_string()];

    let matched =
        matching_cache_volumes(&existing, &cache_volume_name("abc123", ""), &HashSet::new());

    assert!(matched.is_empty());
}

/// `ratect caches list` reports what a `volumes` entry calls a cache,
/// not the prefixed Docker volume name it happens to be stored under —
/// otherwise nothing it prints could be pasted back into `caches clean`.
#[test]
fn list_directory_caches_reports_cache_names_without_the_key_file() {
    let dir = unique_temp_dir();
    let caches_dir = cache_directory(&dir);
    fs::create_dir_all(caches_dir.join("npm-cache")).unwrap();
    fs::create_dir_all(caches_dir.join("gradle-cache")).unwrap();
    fs::write(caches_dir.join("key"), "abc123\n").unwrap();

    assert_eq!(
        list_directory_caches(&dir).unwrap(),
        vec!["gradle-cache", "npm-cache"]
    );

    fs::remove_dir_all(&dir).unwrap();
}

#[test]
fn list_directory_caches_is_empty_for_a_project_with_no_caches() {
    let dir = unique_temp_dir();
    assert!(list_directory_caches(&dir).unwrap().is_empty());
    fs::remove_dir_all(&dir).unwrap();
}

#[test]
fn clean_directory_caches_removes_matching_subdirectories_and_leaves_others() {
    let dir = unique_temp_dir();
    let caches_dir = cache_directory(&dir);
    fs::create_dir_all(caches_dir.join("gradle-cache")).unwrap();
    fs::create_dir_all(caches_dir.join("npm-cache")).unwrap();
    fs::write(caches_dir.join("key"), "abc123\n").unwrap();

    let removed = clean_directory_caches(&dir, &HashSet::new()).unwrap();

    let mut removed = removed;
    removed.sort();
    assert_eq!(removed, vec!["gradle-cache", "npm-cache"]);
    assert!(!caches_dir.join("gradle-cache").exists());
    assert!(!caches_dir.join("npm-cache").exists());
    // The key file is a plain file, not a directory — never matched or
    // removed as if it were a cache.
    assert!(caches_dir.join("key").exists());

    fs::remove_dir_all(&dir).unwrap();
}

#[test]
fn clean_directory_caches_restricts_to_only_when_given() {
    let dir = unique_temp_dir();
    let caches_dir = cache_directory(&dir);
    fs::create_dir_all(caches_dir.join("gradle-cache")).unwrap();
    fs::create_dir_all(caches_dir.join("npm-cache")).unwrap();

    let only = HashSet::from(["npm-cache".to_string()]);
    let removed = clean_directory_caches(&dir, &only).unwrap();

    assert_eq!(removed, vec!["npm-cache"]);
    assert!(caches_dir.join("gradle-cache").is_dir());
    assert!(!caches_dir.join("npm-cache").exists());

    fs::remove_dir_all(&dir).unwrap();
}

#[test]
fn clean_directory_caches_does_nothing_when_the_cache_directory_does_not_exist() {
    let dir = unique_temp_dir();

    let removed = clean_directory_caches(&dir, &HashSet::new()).unwrap();

    assert!(removed.is_empty());

    fs::remove_dir_all(&dir).unwrap();
}

/// A shared cache's volume name carries no project key — that *is* the
/// feature. Two projects resolving the same shared cache must land on one
/// volume, where two projects resolving the same project-scoped cache must
/// not.
#[test]
fn a_shared_cache_resolves_to_the_same_volume_for_every_project() {
    let mount = CacheVolumeMount {
        name: "registry".to_string(),
        container: "/registry".to_string(),
        options: None,
        scope: crate::config::CacheScope::Shared,
    };
    let options = CacheOptions {
        cache_type: CacheType::Volume,
        project_directory: PathBuf::from("/irrelevant"),
    };

    let first = resolve_cache_mount(&options, "project-one-key", &mount).unwrap();
    let second = resolve_cache_mount(&options, "project-two-key", &mount).unwrap();

    assert_eq!(first, "ratect-shared-cache-registry:/registry");
    assert_eq!(first, second);
}

/// The prefixes are what keep the two scopes apart in storage, and what
/// stops `--clean`'s project sweep touching a shared cache. Pinned as
/// literals: deriving the expectation from the same function under test
/// would agree with any value it produced.
#[test]
fn the_two_scopes_use_prefixes_that_cannot_match_each_other() {
    let project = cache_volume_name("some-key", "registry");
    let shared = shared_cache_volume_name("registry");

    assert_eq!(project, "batect-cache-some-key-registry");
    assert_eq!(shared, "ratect-shared-cache-registry");

    // The sweep `--clean` performs, against both names.
    let existing = vec![project.clone(), shared.clone()];
    let matched = matching_cache_volumes(
        &existing,
        &cache_volume_name("some-key", ""),
        &HashSet::new(),
    );
    assert_eq!(
        matched,
        vec![project.as_str()],
        "a project sweep must never match a shared cache"
    );
}

/// The shared directory location, pinned by shape rather than exercised:
/// `home_directory()` reads the passwd entry rather than `$HOME`, so a test
/// cannot redirect it without writing into the developer's own home. The
/// sweep and removal machinery underneath is shared with project-scoped
/// directory caches and covered by their tests; what is specific here — and
/// what this pins — is *where* it points.
#[test]
fn a_shared_cache_directory_lives_beside_the_git_include_cache() {
    let root = shared_cache_root().unwrap();
    let home = crate::user::home_directory().unwrap();

    assert_eq!(root, home.join(".ratect").join("caches"));
    assert_eq!(
        shared_cache_directory("registry").unwrap(),
        root.join("registry")
    );
    // `git_include`'s clones sit at `~/.ratect/incl`; both belong to the
    // machine rather than to any one project, which is the whole reason a
    // shared cache cannot live under `.batect/caches` in a project.
    assert_eq!(root.parent().unwrap(), home.join(".ratect"));
}

/// A bare `caches clean` passes an empty name set, which for a *project*
/// cache means "all of them". For a shared one it has to mean "none" —
/// otherwise one project's routine cleanup discards storage every other
/// project is still using.
///
/// This shipped the wrong way round: the rule was written as a precondition
/// on the caller ("`only` is never empty in practice"), which read as
/// satisfied and wasn't. Verifying the documentation against the binary is
/// what caught it, so the rule now lives in the decision function.
#[test]
fn a_shared_cache_is_never_removed_without_being_named() {
    let existing = vec![
        "ratect-shared-cache-registry".to_string(),
        "ratect-shared-cache-other".to_string(),
        "batect-cache-some-key-registry".to_string(),
    ];

    assert!(
        matching_shared_cache_volumes(&existing, &HashSet::new()).is_empty(),
        "an empty name set must match no shared cache"
    );
    assert_eq!(
        matching_shared_cache_volumes(&existing, &HashSet::from(["registry".to_string()])),
        vec!["ratect-shared-cache-registry"],
        "and naming one must not also match the project cache of the same name"
    );
}
