// Copyright 2026 Orican Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use super::*;

use rand_chacha::rand_core::SeedableRng;
use signature::Verifier;
use ssh_key::EcdsaCurve;

/// Every request below is assembled from the numbers written in [RFC
/// 9987](https://www.rfc-editor.org/rfc/rfc9987) rather than from this
/// module's own constants, and every response is checked the same way.
/// A test that derives its input from the code under test can't tell a
/// correct constant from a wrong one — both sides would move together.
const REQUEST_IDENTITIES: u8 = 11;
const IDENTITIES_ANSWER: u8 = 12;
const SIGN_REQUEST: u8 = 13;
const SIGN_RESPONSE: u8 = 14;
const FAILURE: u8 = 5;
const RSA_SHA2_256_FLAG: u32 = 2;
const RSA_SHA2_512_FLAG: u32 = 4;

/// A deterministic key, so a failure is always the same failure. The
/// seed carries no meaning beyond being fixed.
fn test_key(seed: u8, comment: &str) -> LoadedKey {
    let mut rng = rand_chacha::ChaCha20Rng::from_seed([seed; 32]);
    let mut key = PrivateKey::random(&mut rng, Algorithm::Ed25519).unwrap();
    key.set_comment(comment);
    LoadedKey {
        blob: key.public_key().to_bytes().unwrap(),
        comment: comment.to_string(),
        key,
    }
}

/// A deterministic key on the given curve — same reasoning as
/// [`test_key`], and fast enough to generate per test unlike RSA below.
fn test_ecdsa_key(curve: EcdsaCurve) -> LoadedKey {
    let mut rng = rand_chacha::ChaCha20Rng::from_seed([7; 32]);
    let key = PrivateKey::random(&mut rng, Algorithm::Ecdsa { curve }).unwrap();
    LoadedKey {
        blob: key.public_key().to_bytes().unwrap(),
        comment: key.comment().to_string(),
        key,
    }
}

/// A throwaway 2048-bit RSA key, generated by `ssh-keygen` for these
/// tests alone and never used to authenticate to anything. Embedded
/// rather than generated: RSA key generation takes tens of seconds in an
/// unoptimized test build, where an Ed25519 key is instant.
const TEST_RSA_KEY: &str = "\
-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAQEA2Hy24J/ZN803X2Yy5mg3+eHVD4XhPcvjDa7fTpkndBFGl4g/+0es
NPNTdGJIJ3CSlVOMfChfIzlvYy8G8Dd7UlMT+pgxMQ0fUtaTVZ5eI71YIW3WEV9leDR9TZ
NPVFpzEvihoXdiSQpNGzD3xd4lJVYXEAKt9nYo/uTIcFrPWDVLQQwbLRVeJ1pysCS5Iabr
Jzk11f+u+C2bFeyYaVx00jc33x5HIihjJZkSs6nXOVMRhPX6x+LynrWJkH/iRztsgZJk49
7JcqH80+w8ZqYGOs1qIaiDH62NznhJ9LUND235Enr0cIeYk6jRnjbGy7Hn3m54+Q5z+wK2
89FTCHkVyQAAA8j1uSZ39bkmdwAAAAdzc2gtcnNhAAABAQDYfLbgn9k3zTdfZjLmaDf54d
UPheE9y+MNrt9OmSd0EUaXiD/7R6w081N0YkgncJKVU4x8KF8jOW9jLwbwN3tSUxP6mDEx
DR9S1pNVnl4jvVghbdYRX2V4NH1Nk09UWnMS+KGhd2JJCk0bMPfF3iUlVhcQAq32dij+5M
hwWs9YNUtBDBstFV4nWnKwJLkhpusnOTXV/674LZsV7JhpXHTSNzffHkciKGMlmRKzqdc5
UxGE9frH4vKetYmQf+JHO2yBkmTj3slyofzT7DxmpgY6zWohqIMfrY3OeEn0tQ0PbfkSev
Rwh5iTqNGeNsbLsefebnj5DnP7Arbz0VMIeRXJAAAAAwEAAQAAAQBBS8SBFdWXnh8geBvM
IQ0ZIoN37iKU2AVA4EjcVRdwS7GmDON3cBPB2M6IIQiwVKTxw0RxQmAHqNAu80U9eQ6KMy
Koh/T2XYXgH3ZK8bxlPTvywUU68jIRwos0tcTMpYdl5nYh1HdhnmjJVci19p3vl/rWymgc
GWGeF/VY5hr5+HMD/+AKRnD1usH7QOtqBa2LBmfEcG4a3c3Hp7F9euENtYaaiT9C4d1RwS
M481Z1d9rwillV8kAUxA1Xg4ltDI9h9rTF4/IU16Iq8GgM+UkVi19ZGwwTZrUKlP+A1ksP
GMjjbKz9GbLDP3gqFw/8RJ7KevLnSW4xD7i11n5pHi8dAAAAgAVQzJMUZEhd6Akts3sjaF
qKDFreHoTtjI61ekTHg+HSYT48xx+KWmXXREO9QBOTOqaOj8wiMKeUYw/w3Dsd5BEpXOhr
TZ7YiLceOnFG3+XGyQ9DZfsn8dPTLxihsEGYbfNKJuPmNllMDlGJgdqjRIDhZ5eFyWRdB8
WwMl6bj8BUAAAAgQDzwsJbLMbZDiKkFvqF7KcyKF9glPYrcR1fzoDZUJJoNfEaSKhCjtGR
gxI/9ccbF8Gdf9fmIj1KZnb03dZS60Mdjxa/UsoGuuRNf5rHe8ZO8pLyENkd3gKr1F2qtZ
LMJY54dqnMHvZ3db9jUSb2uS9j3Ij3TnB1q70iKR25KK6qSwAAAIEA41tjCuTozPlCRmtv
w3Rka90qlZ2OQNOko+c3M+/56/d0GZ+8W1Gf79qs/V/4u64r+lDChQFK+YZtW6en2ew+L4
woLocI7INRyn4uUjRGbbkuFuBHMFVbDDtgO18gBwFQ8HZySXZ7IKoM30BXUEgeXaH1s/2T
fzqxqMSMGQFJc7sAAAAMcnNhLXRlc3Qta2V5AQIDBAUGBw==
-----END OPENSSH PRIVATE KEY-----
";

fn test_rsa_key() -> LoadedKey {
    let key = PrivateKey::from_openssh(TEST_RSA_KEY).unwrap();
    LoadedKey {
        blob: key.public_key().to_bytes().unwrap(),
        comment: key.comment().to_string(),
        key,
    }
}

fn sign_request(blob: &[u8], data: &[u8], flags: u32) -> Vec<u8> {
    let mut request = vec![SIGN_REQUEST];
    write_string(&mut request, blob);
    write_string(&mut request, data);
    request.extend_from_slice(&flags.to_be_bytes());
    request
}

/// Unwraps a `SSH_AGENT_SIGN_RESPONSE`, returning the signature's
/// algorithm name and its raw blob — the `string algorithm` +
/// `string blob` pair RFC 9987 §5.3 defines.
fn signature_parts(response: &[u8]) -> (String, Vec<u8>) {
    assert_eq!(response[0], SIGN_RESPONSE, "not a sign response");
    let mut reader = Reader::new(&response[1..]);
    let signature = reader.string().expect("truncated signature");
    let mut inner = Reader::new(signature);
    let algorithm = inner.string().expect("no signature algorithm");
    let blob = inner.string().expect("no signature blob");
    (
        String::from_utf8(algorithm.to_vec()).unwrap(),
        blob.to_vec(),
    )
}

/// The identities answer's exact wire layout: the message number, a
/// `uint32` key count, then one `string` public blob and `string`
/// comment per key, in order.
#[test]
fn listing_identities_returns_every_key_with_its_comment() {
    let keys = vec![test_key(1, "first-key"), test_key(2, "second-key")];

    let response = respond(&keys, &[REQUEST_IDENTITIES]);

    assert_eq!(response[0], IDENTITIES_ANSWER);
    let mut reader = Reader::new(&response[1..]);
    assert_eq!(reader.u32(), Some(2));
    for key in &keys {
        assert_eq!(reader.string(), Some(key.blob.as_slice()));
        assert_eq!(reader.string(), Some(key.comment.as_bytes()));
    }
    assert_eq!(reader.take(1), None, "unexpected trailing bytes");
}

/// An agent holding nothing still answers, rather than failing — that's
/// how a client learns there is nothing to try.
#[test]
fn listing_identities_with_no_keys_answers_with_a_count_of_zero() {
    let response = respond(&[], &[REQUEST_IDENTITIES]);

    assert_eq!(response, vec![IDENTITIES_ANSWER, 0, 0, 0, 0]);
}

/// The signature has to verify against the *public* key, which is the
/// only check that would catch signing the wrong bytes, hashing them
/// differently, or mislabelling the algorithm.
#[test]
fn signing_produces_a_signature_the_public_key_verifies() {
    let keys = vec![test_key(3, "signing-key")];
    let data = b"session identifier and authentication request";

    let response = respond(&keys, &sign_request(&keys[0].blob, data, 0));

    let (algorithm, _) = signature_parts(&response);
    assert_eq!(algorithm, "ssh-ed25519");
    let mut reader = Reader::new(&response[1..]);
    let signature = Signature::try_from(reader.string().unwrap()).unwrap();
    // Fully qualified: `PublicKey` has an inherent `verify` for `sshsig`
    // signatures that would otherwise shadow the trait method.
    Verifier::verify(keys[0].key.public_key(), data, &signature)
        .expect("the signature should verify against the public key");
}

/// The ECDSA curves are enabled as `ssh-key` features and accepted by
/// [`load_keys`], so each one needs a signature that actually verifies —
/// the features cost dependencies, and "it compiles" is not evidence the
/// path works. Signing goes through `try_sign` here rather than
/// [`rsa_signature`], and RFC 9987's flags are RSA-only, so a client
/// sending flags with an ECDSA key must still get its one valid
/// signature format back rather than a failure.
#[test]
fn signing_with_an_ecdsa_key_verifies_on_every_supported_curve() {
    for (curve, expected) in [
        (EcdsaCurve::NistP256, "ecdsa-sha2-nistp256"),
        (EcdsaCurve::NistP384, "ecdsa-sha2-nistp384"),
        (EcdsaCurve::NistP521, "ecdsa-sha2-nistp521"),
    ] {
        let keys = vec![test_ecdsa_key(curve)];
        let data = b"session identifier and authentication request";

        let response = respond(&keys, &sign_request(&keys[0].blob, data, RSA_SHA2_512_FLAG));

        let (algorithm, _) = signature_parts(&response);
        assert_eq!(algorithm, expected);
        let mut reader = Reader::new(&response[1..]);
        let signature = Signature::try_from(reader.string().unwrap()).unwrap();
        Verifier::verify(keys[0].key.public_key(), data, &signature)
            .unwrap_or_else(|_| panic!("the {expected} signature should verify"));
    }
}

/// RFC 9987's flags exist for RSA alone, and getting them wrong is
/// invisible until a real server rejects the signature: the algorithm
/// name in the response has to match the hash actually used, so both
/// halves are checked.
#[test]
fn signing_with_an_rsa_key_honours_the_requested_sha2_algorithm() {
    let keys = vec![test_rsa_key()];
    let data = b"session identifier and authentication request";

    for (flags, expected) in [
        (RSA_SHA2_512_FLAG, "rsa-sha2-512"),
        (RSA_SHA2_256_FLAG, "rsa-sha2-256"),
    ] {
        let response = respond(&keys, &sign_request(&keys[0].blob, data, flags));

        let (algorithm, _) = signature_parts(&response);
        assert_eq!(algorithm, expected, "for flags {flags}");
        let mut reader = Reader::new(&response[1..]);
        let signature = Signature::try_from(reader.string().unwrap()).unwrap();
        Verifier::verify(keys[0].key.public_key(), data, &signature)
            .unwrap_or_else(|_| panic!("the {expected} signature should verify"));
    }
}

/// No flags means the legacy SHA-1 `ssh-rsa` algorithm, which this
/// agent refuses — see [`rsa_signature`]. Answering with a SHA-2
/// signature instead would be worse than failing: the client asked for
/// one algorithm and would be told it got another.
#[test]
fn signing_with_an_rsa_key_refuses_the_legacy_sha1_algorithm() {
    let keys = vec![test_rsa_key()];

    let response = respond(&keys, &sign_request(&keys[0].blob, b"data", 0));

    assert_eq!(response, vec![FAILURE]);
}

/// A client picks the key to sign with by its public blob, so a blob
/// this agent doesn't hold must fail rather than being served by
/// whichever key happens to be first.
#[test]
fn signing_with_an_unknown_key_fails() {
    let keys = vec![test_key(4, "held-key")];
    let other = test_key(5, "not-held-key");

    let response = respond(&keys, &sign_request(&other.blob, b"data", 0));

    assert_eq!(response, vec![FAILURE]);
}

/// A truncated request must be answered, not crash the agent or hang
/// the connection — `Reader` bounds-checks every read for this reason.
#[test]
fn a_truncated_sign_request_fails_rather_than_panicking() {
    let keys = vec![test_key(6, "key")];
    let full = sign_request(&keys[0].blob, b"data", 0);

    for length in 0..full.len() {
        assert_eq!(
            respond(&keys, &full[..length]),
            vec![FAILURE],
            "a {length}-byte prefix of a sign request should fail"
        );
    }
}

/// Writes `key` out in OpenSSH's own private key format, so `load_key`
/// is exercised against a real file rather than an in-memory value.
fn write_key_file(directory: &Path, name: &str, key: &PrivateKey) -> PathBuf {
    std::fs::create_dir_all(directory).unwrap();
    let path = directory.join(name);
    std::fs::write(
        path.as_path(),
        key.to_openssh(ssh_key::LineEnding::LF).unwrap(),
    )
    .unwrap();
    path
}

fn unique_temp_dir() -> PathBuf {
    std::env::temp_dir().join(format!("ratect-ssh-agent-test-{}", uuid::Uuid::new_v4()))
}

/// The comment is what `ssh-add -l` shows inside the build, so it has
/// to survive the round trip through the file rather than being
/// replaced by the file's name or left empty.
#[test]
fn loading_a_key_file_keeps_its_public_blob_and_comment() {
    let directory = unique_temp_dir();
    let key = test_key(8, "loaded-from-a-file").key;
    let path = write_key_file(&directory, "id_ed25519", &key);

    let loaded = load_keys(&[path]).unwrap();

    assert_eq!(loaded.len(), 1);
    assert_eq!(loaded[0].comment, "loaded-from-a-file");
    assert_eq!(loaded[0].blob, key.public_key().to_bytes().unwrap());
    std::fs::remove_dir_all(&directory).unwrap();
}

/// A throwaway Ed25519 key protected by the passphrase
/// `test-passphrase`, generated by `ssh-keygen` for this test alone.
/// Embedded because it can't be produced from within the test: writing
/// an encrypted key needs `ssh-key`'s `encryption` feature, which is
/// deliberately off (it alone would pull in ~16 crates for a case this
/// agent refuses anyway).
const TEST_ENCRYPTED_KEY: &str = "\
-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABBxmy6fV3
HZgz7Icu2B7IjIAAAAGAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIMx6KPDUuTS6adHK
OpqS+OA2lOuWVU/GJZ5lc2DYVdalAAAAoMkFaWwGgNBB6/IprP+RAEYdk/bvEAQcovvVwF
3bR6Fdw1/wm9O9oDi73gRFDg9Fk0uHP0X4REspg2m4UcPdq84Ca7TVaV78xC7+db4YY3Ec
10Cc3OG3w2f3VkIVIFdgPW6iMy88u5jP2aLqHnKuJLjhqcvWE1lnhMWvG0baB58PWRHe4s
wq5n6O9bZ1kNQ1vKBt7358x8sWgvoxUAOLDF0=
-----END OPENSSH PRIVATE KEY-----
";

/// There is no terminal to prompt on during a build, so a
/// passphrase-protected key has to be refused *at load*, naming the
/// file. Left to signing time it would surface as an unexplained
/// authentication failure deep inside someone's Dockerfile.
#[test]
fn loading_a_passphrase_protected_key_is_refused_and_names_the_file() {
    let directory = unique_temp_dir();
    std::fs::create_dir_all(&directory).unwrap();
    let path = directory.join("id_ed25519");
    std::fs::write(&path, TEST_ENCRYPTED_KEY).unwrap();

    let error = load_keys(std::slice::from_ref(&path)).unwrap_err();

    let message = format!("{error:#}");
    assert!(
        message.contains("passphrase"),
        "unexpected error: {message}"
    );
    assert!(
        message.contains(&path.display().to_string()),
        "the error should name the file, but was: {message}"
    );
    std::fs::remove_dir_all(&directory).unwrap();
}

/// A missing or unreadable key has to name the file — this is the error
/// a user sees when a `paths` entry points at the wrong place, and
/// "failed to read a key" would leave them guessing which one.
#[test]
fn loading_a_missing_key_file_names_it() {
    let path = unique_temp_dir().join("absent_key");

    let error = load_keys(std::slice::from_ref(&path)).unwrap_err();

    assert!(
        format!("{error}").contains(&path.display().to_string()),
        "the error should name the missing file, but was: {error}"
    );
}

/// The whole path, not just the directory, has to fit `sun_path` — so
/// the check has to include the socket's own file name.
#[test]
fn a_socket_path_longer_than_the_unix_limit_is_rejected() {
    let long = PathBuf::from("/tmp").join("d".repeat(120)).join("agent");

    let error = check_socket_path_length(&long).unwrap_err();

    assert!(
        format!("{error}").contains("too long"),
        "unexpected error: {error}"
    );
    check_socket_path_length(Path::new("/tmp/ratect-ssh-0123456789ab/agent"))
        .expect("a realistic socket path should be accepted");
}

/// Add, remove, lock, unlock, smartcard and extension requests all land
/// here: this agent implements none of them, and a client is entitled
/// to an answer rather than a dropped connection.
#[test]
fn an_unimplemented_request_fails() {
    let keys = vec![test_key(7, "key")];

    // 17 is SSH_AGENTC_ADD_IDENTITY; 25 is SSH_AGENTC_EXTENSION.
    for request_type in [17u8, 18, 22, 23, 25] {
        assert_eq!(respond(&keys, &[request_type]), vec![FAILURE]);
    }
    assert_eq!(respond(&keys, &[]), vec![FAILURE], "empty request");
}

/// Sends one length-prefixed request and reads the length-prefixed
/// response back, the way BuildKit's forwarded stream will.
async fn round_trip(stream: &mut UnixStream, request: &[u8]) -> Vec<u8> {
    stream
        .write_all(&(request.len() as u32).to_be_bytes())
        .await
        .unwrap();
    stream.write_all(request).await.unwrap();

    let mut length = [0u8; 4];
    stream.read_exact(&mut length).await.unwrap();
    let mut response = vec![0u8; u32::from_be_bytes(length) as usize];
    stream.read_exact(&mut response).await.unwrap();
    response
}

/// The four-byte length prefix in each direction, the connection's own
/// request loop, the directory's permissions and the cleanup on drop
/// are only exercised by a real connection over a real socket — so this
/// drives one, rather than calling [`respond`] directly as the tests
/// above do.
#[tokio::test]
async fn a_client_can_talk_to_the_agent_over_its_socket() {
    use std::os::unix::fs::PermissionsExt;

    let directory = unique_temp_dir();
    let key = test_key(10, "over-the-socket").key;
    let key_file = write_key_file(&directory, "id_ed25519", &key);

    let keyring = Keyring::start(&[key_file]).await.unwrap();
    let socket_directory = keyring.socket_path().parent().unwrap().to_path_buf();

    // The socket grants signing to anything that can reach it, so the
    // directory holding it must not be traversable by other users.
    let mode = std::fs::metadata(&socket_directory)
        .unwrap()
        .permissions()
        .mode();
    assert_eq!(
        mode & 0o777,
        0o700,
        "the agent's directory should be private to this user"
    );

    // The second, independent barrier. `bind` leaves the socket at the
    // process umask (commonly `0755`), which the directory above
    // already covers — but resting the whole protection on one `mode`
    // argument is what this guards against, and it is what OpenSSH's
    // own agent does too.
    let socket_mode = std::fs::metadata(keyring.socket_path())
        .unwrap()
        .permissions()
        .mode();
    assert_eq!(
        socket_mode & 0o777,
        0o600,
        "the socket itself should be private to this user"
    );

    let mut stream = UnixStream::connect(keyring.socket_path()).await.unwrap();

    let response = round_trip(&mut stream, &[REQUEST_IDENTITIES]).await;
    assert_eq!(response[0], IDENTITIES_ANSWER);
    let mut reader = Reader::new(&response[1..]);
    assert_eq!(reader.u32(), Some(1));
    assert_eq!(
        reader.string(),
        Some(key.public_key().to_bytes().unwrap().as_slice())
    );
    assert_eq!(reader.string(), Some(b"over-the-socket".as_slice()));

    // A client sends many requests down one connection, so the second
    // has to be answered as readily as the first.
    let blob = key.public_key().to_bytes().unwrap();
    let response = round_trip(&mut stream, &sign_request(&blob, b"data", 0)).await;
    assert_eq!(response[0], SIGN_RESPONSE);

    drop(keyring);
    assert!(
        !socket_directory.exists(),
        "dropping the agent should remove its socket directory"
    );

    std::fs::remove_dir_all(&directory).unwrap();
}

/// Dropping the agent has to stop the connections it is *already*
/// serving, not just the accept loop. A detached task per connection
/// leaves an open client able to keep getting signatures after the
/// build that needed the keys has finished — the socket file is gone,
/// but an established connection doesn't care.
#[tokio::test]
async fn dropping_the_agent_stops_a_connection_it_is_already_serving() {
    let directory = unique_temp_dir();
    let key = test_key(11, "still-connected").key;
    let key_file = write_key_file(&directory, "id_ed25519", &key);

    let keyring = Keyring::start(&[key_file]).await.unwrap();
    let mut stream = UnixStream::connect(keyring.socket_path()).await.unwrap();

    // Establish the connection properly first: a client that has never
    // been served would prove nothing about tearing one down.
    let response = round_trip(&mut stream, &[REQUEST_IDENTITIES]).await;
    assert_eq!(response[0], IDENTITIES_ANSWER);

    drop(keyring);

    // The abort has to land before the peer is observably gone.
    tokio::task::yield_now().await;
    let mut length = [0u8; 4];
    stream
        .write_all(&[0, 0, 0, 1, REQUEST_IDENTITIES])
        .await
        .ok();
    let read = tokio::time::timeout(
        std::time::Duration::from_secs(5),
        stream.read_exact(&mut length),
    )
    .await
    .expect("the dropped agent should not leave the client waiting");

    assert!(
        read.is_err(),
        "the connection should be closed, but it answered {length:?}"
    );

    std::fs::remove_dir_all(&directory).unwrap();
}
